export const SET_MOVIES_INIT = 'SET_MOVIES_INIT';
export const SET_MOVIES_SUCCESS = 'SET_MOVIES_SUCCESS';
export const SET_MOVIES_FAIL = 'SET_MOVIES_FAIL';
export const GET_MOVIE = 'GET_MOVIE';
export const CHANGE_API = 'CHANGE_API';
export const GET_CREW = 'GET_CREW';
export const RESET = 'RESET';
export const PAGE_PLUS = 'PAGE_PLUS';
export const PAGE_MINUS = 'PAGE_MINUS';
export const RESET_PAGE = 'RESET_PAGE';

export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_FAIL = 'SEARCH_MOVIE_FAIL';
export const SET_NAME = 'SET_NAME';
export const RESET_MOVIES = 'RESET_MOVIES';
export const RESET_ERROR = 'RESET_ERROR';


export const INIT_DISCOVER = 'INIT_DISCOVER';
export const DISCOVER_MOVIES_SUCCESS = 'DISCOVER_MOVIES_SUCCESS';
export const DISCOVER_MOVIES_FAIL = 'DISCOVER_MOVIES_FAIL';
export const DISCOVER_SERIES_SUCCESS = 'DISCOVER_SERIES_SUCCESS';
export const DISCOVER_SERIES_FAIL = 'DISCOVER_SERIES_FAIL';
export const STORE_TRAILER = 'STORE_TRAILER';
export const RESET_TRAILER = 'RESET_TRAILER';

export const INIT_PERSON = 'INIT_PERSON';
export const SET_PERSON = 'SET_PERSON';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const SET_PERSON_ID = 'SET_PERSON_ID';
export const SET_PERSON_MOVIES = 'SET_PERSON_MOVIES';
export const SET_PERSON_TV = 'SET_PERSON_TV';
export const RESET_PERSON = 'RESET_PERSON';

